name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run:  npm install
      
    - name: Build Trello_app
      run:  npm run build
      
    - name: Check out code
    - uses: actions/checkout@v4
      
    - name: Build Docker image/push to Dockerhub registery
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: neilchampion/Trello_app_Demo
        registery: docker.io
        tags: leatest 
        dockerfile: Dockerfile
        Username: 
        Password:
        
