on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install
      
    - name: Build Trello_app
      run: npm run build
      
    - name: Build Docker image/push to Dockerhub registry
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: neilchampion/trello_app_image
        registry: docker.io
        tag: latest
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/trello_app_image .

   
